### PR TITLE
Don't override shape for empty tensors

### PR DESCRIPTION
**Pull request by tanmayv25**
Allows user to pass an empty shape with no tensor data.

### CODE REVIEW

**Comment by rmccorm4** [comment]
Will it be up to each backend to decide whether an empty output tensor is valid then?

ex: python backend doesn't seem to allow it: https://github.com/triton-inference-server/python_backend/blob/28c9226b51aedaa8c4381e781ecf073e799a146c/src/infer_response.cc#L44

**Comment by Tabrizian** [comment]
I think it should be fine with tensors pointing to the nullptr. it Yes, as you mentioned that line was specifically added to disallow passing `None` as the input/output tensors. I believe it is being tested here:

https://github.com/triton-inference-server/server/blob/270b9db032c96631c60957083766f4746c5d240b/qa/python_models/bls/model.py#L239

**Comment by tanmayv25** [comment]
> Will it be up to each backend to decide whether an empty output tensor is valid then?

Yes. These common utilities, triton core and the frontend  supports the [0] shaped tensors. The specific handling will depend upon the backend implementation that is more closer to the model and the framework.

**Review by rmccorm4 — COMMENTED** [review]
Can we add a CI test for empty output as well? It doesn't necessarily have to block this PR if the fix is needed ASAP.

**Comment by tanmayv25** [comment]
I have created DLIS-3740 to include empty tensor testing for TF backend that will exercise the pipeline. At present, we need to generate a TF model that returns an empty tensor.  We can also, use our own custom backend to test this but I wanted to avoid repeated work.

**Review by rmccorm4 — APPROVED** [review]

**Pull request closed without merging**
